### PR TITLE
Fix bookmarklet redirect

### LINKED ISSUE #578: [Bookmarklet] - On sign in, user is not redirected back to the save window

### PR DESCRIPTION
**Pull request by broskoski**
Closes #578

### CODE REVIEW

File: apps/marklet/routes.coffee [hunk 1]
```diff
@@ -3,7 +3,7 @@ validator = require 'validator'
 Backbone = require 'backbone'
 
 @save = (req, res) ->
-  return res.redirect "/log_in?redirect_uri=#{req.url}" unless req.user?
+  return res.redirect "/log_in?redirect-to=#{req.url}" unless req.user?
```
Comment (dzucconi) [inline apps/marklet/routes.coffee]: woof

Comment (broskoski) [inline apps/marklet/routes.coffee]: yap
