### PR TITLE
Fix for channels with special characters in the title

### LINKED ISSUE #1596: & not displaying on channel view and connect interface (works on feed)
## Steps to replicate
https://www.are.na/reginald-dankwa/predominantly-red-black-album-covers

## Expected result
`&`

## Actual result
`&amp;`

### PR DESCRIPTION
**Pull request by broskoski**
Closes #1596

### CODE REVIEW

File: react/components/ManageChannel/index.js [hunk 1]
```diff
@@ -117,6 +117,8 @@ class ManageChannel extends Component {
 
     const { data: { channel } } = this.props;
 
+    console.log('channel', unescape(channel.title));
```
Comment (dzucconi) [inline react/components/ManageChannel/index.js]: loggy

Comment (broskoski) [reply react/components/ManageChannel/index.js]: thank ye
