### PR TITLE
Fixes welcome regex (closes #1257)

### LINKED ISSUE #1257: Clicking links in the sidebar in the welcome tutorial breaks backbone.history
## Steps to replicate
1. Navigate to [the welcome page](https://www.are.na/welcome/channels)
2. Click any of the links in the sidebar other than `2. Connecting`

This results in this uncaught error: `Backbone.history has already been started`

## Expected result
Those links should take you to the page required

## Actual result
Errors out and the site doesn't load.

### PR DESCRIPTION
**Pull request by broskoski**

### CODE REVIEW

File: components/layout/client.coffee [hunk 1]
```diff
@@ -54,7 +54,7 @@ initGlobalBlockRouting = ->
     /^\/reset(\/\w+)?$/
     /^\/confirm(\/\w+)?$/
     /^\/register(\/\w+)?$/
-    /^\/welcome(\/\w+)?$/
+    /^\/welcome(\/.*)?$/
```
Comment (dzucconi) [inline components/layout/client.coffee]: `^\/welcome(\/(\w|-)+)?`

Would be more accurate for URLs.

You can also change all of these to that.
