### PR TITLE
Quick group fixes

### LINKED ISSUE #1655: 'edit channel' modal not working on channels i do not own (but collaborate on)
sometimes the modal doesn't appear at all

sometimes the modal appears but when i mouse over any forms the modal disappears

### PR DESCRIPTION
**Pull request by broskoski**
Closes #1655

### CODE REVIEW

File: react/components/ManageChannel/index.js [hunk 1]
```diff
@@ -141,9 +141,12 @@ class ManageChannel extends Component {
 
     if (loading) return <LoadingIndicator />;
 
-    const { data: { channel, me: { counts } } } = this.props;
+    const { data: { channel, me, me: { counts } } } = this.props;
     const owner = `${channel.owner.__typename.toUpperCase()}:${channel.owner.id}`;
 
+    // Only the original author can change the owner;
+    const showAuthor = counts.groups > 0 && me.id === channel.user.id;
```
Comment (dzucconi) [inline react/components/ManageChannel/index.js]: This is fine for the quick fix but should likely be a `can`

Comment (broskoski) [reply react/components/ManageChannel/index.js]: Indeed
